ALTER TABLE {p}limits
	ADD COLUMN rate INT NOT NULL DEFAULT 0,
	ADD COLUMN per_us BIGINT NOT NULL DEFAULT 0,
	ADD COLUMN burst INT NOT NULL DEFAULT 0,
	ADD COLUMN tat DATETIME(6) NULL,
	ALGORITHM = INSTANT;

ALTER TABLE {p}jobs ADD COLUMN granted BOOLEAN NOT NULL DEFAULT FALSE, ALGORITHM = INSTANT;

ALTER TABLE {p}jobs ADD INDEX jobs_granted (state, granted, limit_key), ALGORITHM = INPLACE, LOCK = NONE;
