ALTER TABLE {p}jobs ADD COLUMN progress SMALLINT NOT NULL DEFAULT 0, ALGORITHM = INSTANT;

ALTER TABLE {p}archive ADD COLUMN progress SMALLINT NOT NULL DEFAULT 0, ALGORITHM = INSTANT;

CREATE TABLE IF NOT EXISTS {p}logs (
	job_id BIGINT NOT NULL,
	seq BIGINT NOT NULL AUTO_INCREMENT,
	attempt INT NOT NULL,
	at DATETIME(6) NOT NULL,
	text TEXT NOT NULL,
	PRIMARY KEY (job_id, seq),
	KEY logs_seq (seq)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_bin;
