package pgstore

type statements struct {
	admit               string
	admitFinished       string
	admitSkip           string
	afterBatches        string
	allocate            string
	archivedParents     string
	attach              string
	batch               string
	batches             string
	busy                string
	children            string
	complete            string
	completeFinished    string
	countDeleted        string
	counts              string
	createRecurring     string
	delete              string
	due                 string
	finish              string
	finishDeps          string
	finishedBatchDeps   string
	fire                string
	fired               string
	hasRecurring        string
	heartbeat           string
	holders             string
	idleBatches         string
	insert              string
	insertDeps          string
	insertDoomed        string
	job                 string
	lead                string
	leases              string
	limits              string
	lockBatches         string
	lockFinishedBatches string
	lockLimits          string
	lockParents         string
	missingLinks        string
	nextDue             string
	notify              string
	now                 string
	openBatch           string
	orphans             string
	pause               string
	paused              string
	promote             string
	pruneArchive        string
	pruneBatches        string
	pruneFailed         string
	pruneHolders        string
	pruneLimits         string
	pruneServers        string
	pruneStats          string
	pruneUniques        string
	queues              string
	reconcile           string
	recurring           string
	recurrings          string
	releaseBatches      string
	removeRecurring     string
	requeueArchived     string
	requeueLive         string
	resign              string
	resolve             string
	seal                string
	series              string
	servers             string
	setMeta             string
	strandedParents     string
	stuck               string
	throttledKeys       string
	unregister          string
	unusedLimits        string
	updateRecurring     string
}

func (q *statements) each(fn func(p *string, text string)) {
	fn(&q.admit, sqlAdmit)
	fn(&q.admitFinished, sqlAdmitFinished)
	fn(&q.admitSkip, sqlAdmitSkip)
	fn(&q.afterBatches, sqlAfterBatches)
	fn(&q.allocate, sqlAllocate)
	fn(&q.archivedParents, sqlArchivedParents)
	fn(&q.attach, sqlAttach)
	fn(&q.batch, sqlBatch)
	fn(&q.batches, sqlBatches)
	fn(&q.busy, sqlBusy)
	fn(&q.children, sqlChildren)
	fn(&q.complete, sqlComplete)
	fn(&q.completeFinished, sqlCompleteFinished)
	fn(&q.countDeleted, sqlCountDeleted)
	fn(&q.counts, sqlCounts)
	fn(&q.createRecurring, sqlCreateRecurring)
	fn(&q.delete, sqlDelete)
	fn(&q.due, sqlDue)
	fn(&q.finish, sqlFinish)
	fn(&q.finishDeps, sqlFinishDeps)
	fn(&q.finishedBatchDeps, sqlFinishedBatchDeps)
	fn(&q.fire, sqlFire)
	fn(&q.fired, sqlFired)
	fn(&q.hasRecurring, sqlHasRecurring)
	fn(&q.heartbeat, sqlHeartbeat)
	fn(&q.holders, sqlHolders)
	fn(&q.idleBatches, sqlIdleBatches)
	fn(&q.insert, sqlInsert)
	fn(&q.insertDeps, sqlInsertDeps)
	fn(&q.insertDoomed, sqlInsertDoomed)
	fn(&q.job, sqlJob)
	fn(&q.lead, sqlLead)
	fn(&q.leases, sqlLeases)
	fn(&q.limits, sqlLimits)
	fn(&q.lockBatches, sqlLockBatches)
	fn(&q.lockFinishedBatches, sqlLockFinishedBatches)
	fn(&q.lockLimits, sqlLockLimits)
	fn(&q.lockParents, sqlLockParents)
	fn(&q.missingLinks, sqlMissingLinks)
	fn(&q.nextDue, sqlNextDue)
	fn(&q.notify, sqlNotify)
	fn(&q.now, sqlNow)
	fn(&q.openBatch, sqlOpenBatch)
	fn(&q.orphans, sqlOrphans)
	fn(&q.pause, sqlPause)
	fn(&q.paused, sqlPaused)
	fn(&q.promote, sqlPromote)
	fn(&q.pruneArchive, sqlPruneArchive)
	fn(&q.pruneBatches, sqlPruneBatches)
	fn(&q.pruneFailed, sqlPruneFailed)
	fn(&q.pruneHolders, sqlPruneHolders)
	fn(&q.pruneLimits, sqlPruneLimits)
	fn(&q.pruneServers, sqlPruneServers)
	fn(&q.pruneStats, sqlPruneStats)
	fn(&q.pruneUniques, sqlPruneUniques)
	fn(&q.queues, sqlQueues)
	fn(&q.reconcile, sqlReconcile)
	fn(&q.recurring, sqlRecurring)
	fn(&q.recurrings, sqlRecurrings)
	fn(&q.releaseBatches, sqlReleaseBatches)
	fn(&q.removeRecurring, sqlRemoveRecurring)
	fn(&q.requeueArchived, sqlRequeueArchived)
	fn(&q.requeueLive, sqlRequeueLive)
	fn(&q.resign, sqlResign)
	fn(&q.resolve, sqlResolve)
	fn(&q.seal, sqlSeal)
	fn(&q.series, sqlSeries)
	fn(&q.servers, sqlServers)
	fn(&q.setMeta, sqlSetMeta)
	fn(&q.strandedParents, sqlStrandedParents)
	fn(&q.stuck, sqlStuck)
	fn(&q.throttledKeys, sqlThrottledKeys)
	fn(&q.unregister, sqlUnregister)
	fn(&q.unusedLimits, sqlUnusedLimits)
	fn(&q.updateRecurring, sqlUpdateRecurring)
}
