ALTER TABLE {p}jobs ADD COLUMN progress INTEGER NOT NULL DEFAULT 0;

ALTER TABLE {p}archive ADD COLUMN progress INTEGER NOT NULL DEFAULT 0;

CREATE TABLE {p}logs (
	job_id INTEGER NOT NULL,
	seq INTEGER NOT NULL,
	attempt INTEGER NOT NULL,
	at INTEGER NOT NULL,
	text TEXT NOT NULL,
	PRIMARY KEY (job_id, seq)
) WITHOUT ROWID;
