ALTER TABLE {p}jobs ADD progress SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE {p}archive ADD progress SMALLINT NOT NULL DEFAULT 0;

CREATE TABLE {p}logs (
	job_id BIGINT NOT NULL,
	seq BIGINT IDENTITY(1, 1) NOT NULL,
	attempt INT NOT NULL,
	at DATETIME2(6) NOT NULL,
	text NVARCHAR(MAX) NOT NULL,
	PRIMARY KEY CLUSTERED (job_id, seq)
);
